language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t thracian22/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true thracian22/docker-react npm run test
